-- 코드를 입력하세요
SELECT
    DISTINCT U.USER_ID,
    U.NICKNAME,
    CONCAT(U.CITY, " ", U.STREET_ADDRESS1, " ", U.STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(U.TLNO,1,3), "-", SUBSTRING(U.TLNO,4,4), "-", SUBSTRING(U.TLNO, 8,11)) AS '전화번호'
FROM USED_GOODS_USER AS U
JOIN USED_GOODS_BOARD AS BOARD
    ON BOARD.WRITER_ID = U.USER_ID
WHERE U.USER_ID in (
        SELECT
        WRITER_ID
       FROM USED_GOODS_BOARD
       GROUP BY WRITER_ID
       HAVING COUNT(*) >=3
      )
ORDER BY USER_ID DESC;