-- 코드를 입력하세요
SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    U.GENDER,
    count(DISTINCT U.USER_ID) as USERS
FROM
    USER_INFO as U
JOIN ONLINE_SALE AS OS
    ON U.USER_ID = OS.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;