-- 코드를 입력하세요
SELECT
    AP.APNT_NO,
    PAT.PT_NAME,
    PAT.PT_NO,
    DOC.MCDP_CD,
    DOC.DR_NAME,
    AP.APNT_YMD
FROM APPOINTMENT AS AP
JOIN DOCTOR AS DOC
    ON DOC.DR_ID = AP.MDDR_ID
JOIN PATIENT AS PAT
    ON PAT.PT_NO = AP.PT_NO
WHERE AP.APNT_CNCL_YN = 'N' AND AP.MCDP_CD = 'CS' AND AP.APNT_YMD LIKE '2022-04-13%'
ORDER BY AP.APNT_YMD;