WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM hours
    WHERE HOUR < 23
)
SELECT 
    HOUR,
    COUNT(AO.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS as AO
RIGHT JOIN hours as H
    ON H.HOUR = HOUR(AO.DATETIME)
GROUP BY HOUR
order by hour;