SELECT
    CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS FILE
JOIN USED_GOODS_BOARD AS BOARD
    ON FILE.BOARD_ID = BOARD.BOARD_ID
WHERE FILE.BOARD_ID IN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
)
ORDER BY FILE.FILE_ID DESC;
